-- 형 변환 함수
-- 현재 날짜를 기본형식과 다른 형태로 출력하기
SELECT SYSDATE, TO_CHAR(SYSDATE,'YYYY-MM-DD') FROM DUAL;
-- 사원들의 입사일을 출력하되 요일까지 함께 출력하기
SELECT HIREDATE, TO_CHAR(HIREDATE, 'YYYY-MM-DD DAY') FROM EMP;
-- 현재 날짜일 시간을 출력하기
SELECT TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') AS CURRENT_DATETIME FROM DUAL;
SELECT TO_CHAR(SYSDATE, 'YYYY-MM-DD AM HH:MI:SS') AS CURRENT_DATETIME FROM DUAL;
--통화 기호를 붙여 출력하기 
SELECT SYSDATE, TO_CHAR(1230000), TO_CHAR(1230000,'L999,999,999') FROM DUAL;
--빈 여백을 0으로 채우기
SELECT SYSDATE, TO_CHAR(123456,'000000000'), TO_CHAR(123456,'999,999,999') FROM DUAL;
--2007년 4월 2일에 입사한 사원을 검색하기 위해서, 수치 데이터를 제시
--SELECT ENAME, HIREDATE FROM EMP WHERE HIREDATE = 20070402;
SELECT ENAME, HIREDATE FROM EMP WHERE HIREDATE = TO_DATE(20070402,'YYYYMMDD');

SELECT TRUNC(SYSDATE - TO_DATE('2019/01/01','YYYY/MM/DD')) FROM DUAL;
--'20,000'과 '10,000'의 차이 값을 알아보기 위해서 빼기 
SELECT TO_NUMBER('20,000','99,999') - TO_NUMBER('10,000','99,999') FROM DUAL;
-- 현재 날짜 알아보기 
SELECT TO_CHAR(SYSDATE,'YYYY/MM/DD') FROM DUAL;
-- 현재 날짜 기준으로 어제와 내일의 날짜 
SELECT TO_CHAR(SYSDATE-1,'YYYY/MM/DD') 어제, 
        TO_CHAR(SYSDATE,'YYYY/MM/DD') 오늘,
        TO_CHAR(SYSDATE+1,'YYYY/MM/DD') 내일 FROM DUAL;
        
-- 특정 날짜(DATE) 를 달(MONTH) 기준으로 버리기 
SELECT TO_CHAR(HIREDATE, 'YYYY/MM/DD') 입사일, TO_CHAR(TRUNC(HIREDATE,'MONTH'),'YYYY/MM/DD') 입사일 FROM EMP;
-- 날짜 사이 개월 수 구하기
SELECT ENAME, SYSDATE 오늘, TO_CHAR(HIREDATE, 'YYYY/MM/DD') 입사일, TRUNC(MONTHS_BETWEEN(SYSDATE, HIREDATE)) 근무달수 FROM EMP;
-- 날짜 사이 개월 수 구하기
SELECT ENAME, TO_CHAR(HIREDATE, 'YYYY/MM/DD') 입사일, TO_CHAR(ADD_MONTHS(HIREDATE,6),'YYYY/MM/DD') "입사 6개월 후" FROM EMP;
-- 오늘 기준 최초 도래하는 수요일 언제인지
SELECT TO_CHAR(SYSDATE, 'YYYY/MM/DD') 오늘, TO_CHAR(NEXT_DAY(SYSDATE,'수요일'), 'YYYY/MM/DD') 수요일 FROM DUAL;
-- 입사한 달 마지막 날 구하기
SELECT ENAME, TO_CHAR(HIREDATE,'YYYY/MM/DD') 입사일, TO_CHAR(LAST_DAY(HIREDATE),'YYYY/MM/DD') "마지막 날짜" FROM EMP;




