-- 테이블 명 변경하기
DROP TABLE emp02;
RENAME emp02 TO emp;
DESC emp02;
-- tester1 / 1234
--USER 데이터 딕셔너리 ay2111!!
SELECT table_name FROM user_tables;
SELECT owner, table_name FROM all_tables;
DROP TABLE emp02;
CREATE TABLE emp02 AS SELECT * FROM emp;
SELECT * FROM emp02;
TRUNCATE TABLE emp02; -- DATA만 삭제. 비우기
SELECT * FROM emp02; 
DESC emp02;
SELECT * FROM TAB;
-- 부서 정보 저장 위한 테이블
CREATE TABLE dept01(
    deptno NUMBER(2),
    dname VARCHAR2(14),
    loc VARCHAR2(13)
);
DESC dept01;
INSERT INTO dept01 VALUES(10,'경리부','서울');
SELECT * FROM dept01;
DELETE dept01 WHERE deptno=10;
INSERT INTO dept01 VALUES(10,'경리부','서울');
INSERT INTO dept01(DEPTNO, LOC, DNAME) VALUES(20,'인천','인사부');

-- 암시적으로 NULL 값 삽입
INSERT INTO DEPT01 (DEPTNO, DNAME) VALUES(30, '인사부');--빠진 부분 NULL값
SELECT * FROM DEPT01;
INSERT INTO DEPT01 VALUES(40,'전산부',NULL);
SELECT * FROM DEPT01;
INSERT INTO DEPT01 VALUES(50,'기획부','');--NULL값
INSERT INTO DEPT01 VALUES(60,'기획부',' ');
SELECT * FROM DEPT01;

DROP TABLE EMP02;
CREATE TABLE EMP02(
    EMPNO NUMBER(4) NOT NULL,    
    ENAME VARCHAR2(10),
    JOB VARCHAR2(9),
    -- MGR NUMBER(4),
    HIREDATE DATE,
    -- SAL NUMBER(7,2),
    -- COMM NUMBER(7,2),
    DEPTNO NUMBER(2)
);
DESC EMP02;
INSERT INTO EMP02 VALUES(1001, '김사랑','사원', '01/03/15', 20);--2015년 3월1일
SELECT * FROM EMP02;
INSERT INTO EMP02 VALUES(1003, '오지호','과장', SYSDATE, 30);
SELECT * FROM EMP02;
INSERT INTO EMP02 VALUES(1002,'한예슬','대리', TO_DATE('2014, 05, 01','YYYY, MM, DD'),20);
SELECT * FROM EMP02;
UPDATE DEPT01 SET DNAME='생산부' WHERE DEPTNO=10;
SELECT * FROM DEPT01;
UPDATE DEPT01 SET DNAME='생산부2', LOC='부산' WHERE DEPTNO=20;
SELECT * FROM DEPT01;

-- 모든 ROW 수정
UPDATE DEPT01 SET DNAME='생산부3';
SELECT * FROM DEPT01;
--WHERE 절로 특정 로우만 삭제하기
DELETE DEPT01 WHERE DEPTNO=10;
SELECT * FROM DEPT01;
-- WHERE 절을 생략하여 모든 로우 삭제 
DELETE DEPT01; 
SELECT * FROM DEPT01;

--트랜잭션 관리 
DROP TABLE EMP02;
CREATE TABLE EMP02 AS SELECT * FROM EMP;
SELECT * FROM EMP02;
DELETE EMP02;
SELECT * FROM EMP02;
ROLLBACK;--이전의 수정/삭제 기록을 다 되될림
SELECT * FROM EMP02;
UPDATE EMP02 SET ENAME='무명' WHERE DEPTNO=20;
DELETE EMP02 WHERE DEPTNO=20;
DELETE EMP02 WHERE DEPTNO=10;
ROLLBACK;
COMMIT;


