--커미션에 NULL이 저장된 사원이 있음을 확인하기
SELECT ENAME, SAL, COMM, DEPTNO FROM EMP ORDER BY DEPTNO;
SELECT ENAME, SAL, COMM, SAL*12+COMM, DEPTNO, NVL(COMM,0),SAL*12+NVL(COMM,0) FROM EMP ORDER BY DEPTNO;
SELECT ENAME, SAL, COMM, NVL2(COMM,SAL*12+COMM,SAL*12) FROM EMP ORDER BY DEPTNO;

SELECT DEPTNO FROM DEPT;
SELECT ENAME, DEPTNO, DECODE(DEPTNO, 10, '경리부', 20,'인사과', 30,'영업부',40,'전산부') AS DNAME FROM EMP;-- DECODE -> MAPPING
SELECT ENAME, DEPTNO,
        CASE WHEN DEPTNO=10 THEN '경리부'
            WHEN DEPTNO=20 THEN '인사과'
            WHEN DEPTNO=30 THEN '영업부'
            WHEN DEPTNO=40 THEN '전산부'
        END AS DNAME
FROM EMP;
SELECT DEPTNO, ROUND(SAL, 3) FROM EMP; 
SELECT SUM(SAL) FROM EMP;
SELECT SUM(SAL) AS "급여총액",
        ROUND(AVG(SAL)) AS "급여평균",
        MAX(SAL) AS "최대급여",
        MIN(SAL) AS "최소급여"
FROM EMP;
SELECT TO_DATE(MAX(HIREDATE),'YY/MM/DD'),
    TO_DATE(MIN(HIREDATE),'YY/MM/DD')
FROM EMP;
SELECT SUM(COMM) AS "커미션 총액" FROM EMP;
SELECT MAX(SAL) FROM EMP;
SELECT MAX(SAL) FROM EMP;
SELECT COUNT(COMM) AS "커미션 받는 사원 수" FROM EMP;
SELECT COUNT(*) AS "전체 사원의 수",
    COUNT(COMM) AS "커미션 받는 사원 수" FROM EMP;
SELECT JOB FROM EMP ORDER BY JOB;
SELECT COUNT(DISTINCT JOB) AS "업무수" FROM EMP;
        