--DDL (Data Definition Language) : CREATE, DESC, ALTER, DROP, MODIFY(TABLE CRUD) 
--DML (Data Manipulation Langauge) : INSERT, SELECT, UPDATE, DELETE (RECORD CRUD)
--DCL (Data Control Language) : 데이터 제어어의 종류로는 COMMIT, ROLLBACK, GRANT, REMOVE(권한삭제) 등
DROP TABLE EMP01;

CREATE TABLE EMP01(
    EMPNO NUMBER(4),
    ENAME VARCHAR2(14),
    SAL NUMBER(7,3)
);
DESC EMP01;
DESC EMP;
--컬럼 추가 
ALTER TABLE EMP01 ADD(BIRTH DATE);
DESC EMP01;
-- 사원 이름 컬럼 크기 변경하기 
ALTER TABLE EMP01 MODIFY ENAME VARCHAR2(30);
DESC EMP01;
ALTER TABLE EMP01 DROP COLUMN ENAME;
DESC EMP01;

DROP TABLE EMP01;
CREATE TABLE EMP01(
    EMPNO NUMBER(4),
    ENAME VARCHAR2(14),
    SAL NUMBER(7,3)
);
INSERT INTO EMP01 VALUES(1,'십윤석',1000);
INSERT INTO EMP01 VALUES(2,'십팔윤석',1000);
INSERT INTO EMP01 VALUES(3,'18윤석',1000);
SELECT * FROM EMP01;
ROLLBACK;
COMMIT;