--제약조건 설정
-- NOT NULL      NULL 허용하지 않음
-- UNIQUE        중복된 값을 허용하지 않는다. 항상 유일한 값을 갖도록 한다.
-- PRIMARY KEY   NULL을 허용하지 않고 중복된 값을 허용하지 않는다. NOT NULL + UNIQUE 조건의 합집합
-- FOREIGN KEY   참조되는 테이블에서 컬럼의 값이 존재하면 허용한다
-- CHECK         저장 가능한 데이터 값의 조건을 지정하여 설정한 값만을 허용한다.

SELECT * FROM DEPT;
INSERT INTO DEPT VALUES(10,'TEST', 'TEST');
INSERT INTO DEPT VALUES(NULL,'TEST', 'TEST');
INSERT INTO DEPT VALUES('60','TEST', 'TEST');
INSERT INTO DEPT VALUES(100,'TEST', 'TEST');
INSERT INTO DEPT VALUES(50,'TEST', 'TEST');
-- CUSTOM 제약조건 
DESC USER_CONSTRAINTS; 
-- 제약조건 살펴보기 
SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME FROM USER_CONSTRAINTS;
SELECT CONSTRAINT_NAME, TABLE_NAME, COLUMN_NAME FROM USER_CONS_COLUMNS;

-- TABLE 삭제
DROP TABLE EMP01;
CREATE TABLE EMP01(
    EMPNO NUMBER(4),
    ENAME VARCHAR2(10),
    JOB VARCHAR2(9),
    DEPTNO NUMBER(2)
);

SELECT * FROM EMP01;
INSERT INTO EMP01 VALUES(NULL, NULL, '사원', 30);
SELECT * FROM EMP01;

DROP TABLE EMP02;
CREATE TABLE EMP02(
    EMPNO NUMBER(4) NOT NULL,
    ENAME VARCHAR2(10) NOT NULL,
    JOB VARCHAR2(9),
    DEPTNO NUMBER(2)
);
INSERT INTO EMP02 VALUES(NULL, NULL, '사원', 30);
DESC EMP02;
INSERT INTO EMP02 VALUES(1000,'허준', '사원', 30);
SELECT * FROM EMP02;

DROP TABLE EMP03;
CREATE TABLE EMP03(
    EMPNO NUMBER(4) UNIQUE,
    ENAME VARCHAR2(10) NOT NULL,
    JOB VARCHAR2(9),
    DEPTNO NUMBER(2)
);

DESC EMP03;
INSERT INTO EMP03 VALUES(1000,'허준','사원',30);
INSERT INTO EMP03 VALUES(1000,'홍길동','과장',20);
INSERT INTO EMP03 VALUES(NULL,'홍길동','과장',20);
INSERT INTO EMP03 VALUES(NULL,'안중근','과장',20);
DROP TABLE EMP03;

CREATE TABLE EMP03(
    EMPNO NUMBER(4) UNIQUE NOT NULL,
    ENAME VARCHAR2(10) NOT NULL,
    JOB VARCHAR2(9),
    DEPTNO NUMBER(2)
);


CREATE TABLE EMP04(
    EMPNO NUMBER(4) CONSTRAINT EMP04_EMPNO_UK UNIQUE,
    ENAME VARCHAR2(10) CONSTRAINT EMP04_ENAME_NN NOT NULL,
    JOB VARCHAR2(9),
    DEPTNO NUMBER(2)
);
SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME
FROM USER_CONSTRAINTS WHERE TABLE_NAME IN('EMP04');

CREATE TABLE EMP05(
    EMPNO NUMBER(4) CONSTRAINT EMP05_EMPNO_PK PRIMARY KEY,
    ENAME VARCHAR2(10) CONSTRAINT EMP05_ENAME_NN NOT NULL,
    JOB VARCHAR2(9),
    DEPTNO NUMBER(2)
);

INSERT INTO EMP05 VALUES(1000,'허준','사원',30);
INSERT INTO EMP05 VALUES(1000,'홍길동','과장',20);
INSERT INTO EMP05 VALUES(NULL,'홍길동','부장',10);
INSERT INTO EMP05 VALUES(5555,'안중근','부장',10);

INSERT INTO EMP05(EMPNO, ENAME, JOB, DEPTNO) VALUES(1010,'홍길동','사원',50);

CREATE TABLE EMP06(
    EMPNO NUMBER(4) CONSTRAINT EMP06_EMPNO_PK PRIMARY KEY,
    ENAME VARCHAR2(10) CONSTRAINT EMP06_ENAME_NN NOT NULL,
    JOB VARCHAR2(9),
    DEPTNO NUMBER(2) CONSTRAINT EMP06_DEPTNO_FK REFERENCES DEPT(DEPTNO)
);

DROP TABLE EMP06;
INSERT INTO EMP06 VALUES(1010,'홍길동','사원',30);
SELECT * FROM EMP06;
INSERT INTO EMP06 VALUES(1011,'홍길동2','사원',70);
SELECT * FROM DEPT;

CREATE TABLE EMP07(
    EMPNO NUMBER(4) CONSTRAINT EMP07_EMPNO_PK PRIMARY KEY,
    ENAME VARCHAR2(10) CONSTRAINT EMP06_ENAME_NN NOT NULL,
    SAL NUMBER(7,2) CONSTRAINT EMP07_SAL_CK CHECK(SAL BETWEEN 500 AND 5000),
    GENDER VARCHAR(1) CONSTRAINT EMP07_GENDER_CK CHECK(GENDER IN('M','F'))
);

INSERT INTO EMP07 VALUES(1000,'허준',600,'M');
INSERT INTO EMP07 VALUES(1001,'허준2',600,'F');
SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, R_CONSTRAINT_NAME, TABLE_NAME, SEARCH_CONDITION
FROM USER_CONSTRAINTS WHERE TABLE_NAME IN('EMP07');

-- DEFAULT 제약 조건
DROP TABLE DEPT01;
CREATE TABLE DEPT01(
    DEPTNO NUMBER(2) PRIMARY KEY,
    DNAME VARCHAR2(14),
    LOC VARCHAR2(13) DEFAULT '서울'
);
INSERT INTO DEPT01 (DEPTNO, DNAME) VALUES(10,'경리부');
SELECT * FROM DEPT01;
